### ISSUE TITLE
zobrazeni dvou dnu 

### ISSUE THREAD

**Issue by Med-fr** [slesinger/HomeAssistant-PREdistribuce#21]
Ahoj,
zprovoznil a integroval jsem do sveho HA vas plugin.
Jen se hloupě zeptám... zda je možné zobrazit současně  dnes + zítra?
Jako příklad uvedu:
Večer se chystám nastavit odložený start pro myčku tak by se mě hodilo kdyby jsem videl zároven na jedne karte "zitra".

Děkuji za info.

**Comment by slesinger** [comment]
Ahoj, v te verzi jak je, tak neni. Taky nam tam rozvrh na zitrek schazel, ale uz jsem vedel uz PRE dlouho nezustanu, tak jsem to nechal byt.

**Comment by hokeson** [comment]
vyřešil jsem to takhle:
do binary_sensor.py jsem přidal za řádek 166
```
a = self.html
self.html = etree.tostring(self.tree.xpath('//div[@id="component-hdo-zitra"]')[0]).decode("utf-8").replace('\n', '').replace('\t', '').replace('"/>', '"></span>')
self.html = self.html.replace('<div class="overflow-bar"></span>', '<div class="overflow-bar"></div>')
self.html = a + self.html
```
asi by to šlo elegantněji, ale funguje to
