### ISSUE TITLE
Handover

### ISSUE THREAD

**Issue by mazzy89** [slesinger/HomeAssistant-PREdistribuce#22]
@slesinger Ahoj Honza,

I noticed that you will no longer be maintaining the custom components. Since I rely on these components and will be living in Prague for the foreseeable future, where PRE manages the electricity distribution, I would like to offer to take over the project.

Looking forward to hearing from you

**Comment by slesinger** [comment]
Hi, that is good to hear thank you. I will assign you owner rights for this repo. You can also fork it and I can update readme file to point to yours. All users will have to switch to your version then.

**Comment by mazzy89** [comment]
Up to you. I do not mind having it under your GitHub. However, if that creates useless noise then I will fork it. Please advice what is the best way for you.

**Comment by dinojascur** [comment]
Hello, was there any handover?  where we can find the up2date version? Thanks!

**Comment by mazzy89** [comment]
hey. yes. there was an handover. Which version are you looking for? I'm planning in the coming days (tomorrow) to release a newer version with the support for 2012.12.

**Comment by dinojascur** [comment]
yeeah hit the 2024.12 lxml issue, will be avaiting for update :) 

could you also close the already solved issues? its makes repo a little bit messy :)

**Comment by mazzy89** [comment]
> could you also close the already solved issues? its makes repo a little bit messy :)

All the issues opened at the moment are valid ;-) 

I'm going to do a cleanup once I will make a newer release.

**Comment by mazzy89** [comment]
The handover has been done. I'm going to close this issue.
