### ISSUE TITLE
Enabling this integration breaks file editor

### ISSUE THREAD

**Issue by grinco** [slesinger/HomeAssistant-PREdistribuce#3]
It most probably is a bug in file editor, not serializing entities probably, however when I enable this integration file editor won't display correctly. I think it has to do something with the fact that you're stroing parsed HTML in the entity.

**Comment by slesinger** [comment]
Are you referring to a file editor in Hassio? I am not using that so cannot help too much. My suspicion goes to the hacky html code. What happens if you remove the html? Would any way of escaping help? Please let me know if you find out what works for you.

**Comment by grinco** [comment]
Yes, that's exactly the reason. If I set the HTML entity to an empty sting it starts working again. Escapeing it should help, or you can add an option to disable the HTML entity all together. It has little value in my opinion.

**Comment by ofinka82** [comment]
I had the same problem. For me it was the binary_sensor setting in /config/configuration.yaml. I changed binary_sensor to sensor and everything works now :-)

**Comment by PKEnergy** [comment]
File editor's issue with special characters bugfixed in version 5.4.2.
